version: "3"
services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "${NGINX_HTTP_PORT_HOST}:80"
      - "${NGINX_HTTPS_PORT_HOST}:443"
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
      - ${NGINX_LOG_PATH_HOST}:/var/log/nginx
      - ${NGINX_CONFD_PATH}:/etc/nginx/conf.d
    environment:
      TZ: "$TZ"
    networks:
      extnetwork:
        ipv4_address: 10.1.0.100
  php:
    build:
      context: ./php
    container_name: php
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
      - ./package:/usr/src/
    environment:
      - TZ=Asia/Shanghai
    working_dir: /var/www/
    networks:
      - extnetwork
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=test
    networks:
      - extnetwork
     
networks:
  extnetwork:
    ipam:
      config:
        - subnet: 10.1.0.0/16