version: "3"
services:
  php:
    build:
      context: ./php
    networks:
      - default
    volumes:
      - ./app:/var/www/docker-lnmp-demo
    environment:
      - TZ=Asia/Shanghai
    working_dir: /var/www/docker-lnmp-demo
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=test
    networks:
      - default
     
networks:
  default: