version: "3"
services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
      - ${NGINX_LOG_PATH_HOST}:/var/log/nginx
      - ${NGINX_CONFD_PATH}:/etc/nginx/conf.d
    environment:
      TZ: "$TZ"
    #networks:
      #extnetwork:
        #ipv4_address: 172.16.238.10
    ports:
      - "${NGINX_HTTP_PORT_HOST}:80"
      - "${NGINX_HTTPS_PORT_HOST}:443"
  php:
    build:
      context: ./php
    container_name: php
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
      - ./package:/usr/src/
      - ./php/php.ini:/usr/local/etc/php/php.ini
    environment:
      - TZ=Asia/Shanghai
    working_dir: /var/www/
    #networks:
      #extnetwork:
        #ipv4_address: 172.16.238.11
    extra_hosts:
      dandelion.localhost: 127.0.0.1
      dandelion-merchant.localhost: 127.0.0.1
  #mysql:
    #image: mysql:5.7
    #container_name: mysql
    #volumes:
      #- /apps/mysql/mydir:/mydir
      #- /apps/mysql/datadir:/var/lib/mysql
      #- /apps/mysql/conf/my.cnf:/etc/my.cnf
      # 数据库还原目录 可将需要还原的sql文件放在这里
      #- ./data:/docker-entrypoint-initdb.d
    #environment:
      #- MYSQL_ROOT_PASSWORD=123
      #- MYSQL_DATABASE=dingdong_smart
    #ports:
      # 使用宿主机的3306端口映射到容器的3306端口
      # 宿主机：容器
      #- 3306:3306
    #networks:
      #extnetwork:
        #ipv4_address: 172.16.238.12
  redis:
    build:
      context: ./redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    #networks:
      #extnetwork:
        #ipv4_address: 172.16.238.13
    sysctls:
      - net.core.somaxconn=1024
      - net.ipv4.tcp_syncookies=0

#networks:
  #extnetwork:
    #ipam:
      #config:
        #- subnet: 172.16.238.0/16
#        aux_addresses:
#          dandelion.localhost: 172.16.238.10
#          dandelion-merchant.localhost: 172.16.238.10

